# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test Pull Requests
permissions:
  contents: read

on:
  pull_request:
    branches: ["main"]

concurrency:
  group: pr-ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  review-dependabot-pr:
    uses: JaCraig/Centralized-Workflows/.github/workflows/nodejs-test.yml@main
