# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: NPM Publish

on:
  push:
    branches: [ "main" ]

env:
  GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPMTOKEN }}

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v5

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        registry-url: 'https://registry.npmjs.org/'
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        token: ${{ secrets.NPMTOKEN }}
        
    - run: npm ci

    - run: npm test

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results-${{ matrix.node-version }}
        path: TestResults-${{ matrix.node-version }}

    - name: Update versioning with semantic-release
      run: npx semantic-release
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPMTOKEN }}