# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Document Site Publish

on:
  push:
    branches: ["main"]
    paths:
      - "README.md"
      - "src/**"
      - "package.json"
      - ".github/workflows/typedoc.yml"

concurrency:
  group: typedoc-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  review-dependabot-pr:
    uses: JaCraig/Centralized-Workflows/.github/workflows/typedoc.yml@main
    secrets:
      token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
